sudo: required

language: python
python:
  -  "3.7"

services:
  - docker

script:
  - docker-compose build
  - docker-compose run --rm norwegianblue pytest

# after_success:
#   - bash <(curl -s https://raw.githubusercontent.com/sesam-community/guidelines/master/after_success.sh)
